export default {
  GET_GLOBAL_INFO: 'GET_GLOBAL_INFO',
  GET_GLOBAL_INFO_REQUEST: 'GET_GLOBAL_INFO_REQUEST',
  GET_GLOBAL_INFO_SUCCESS: 'GET_GLOBAL_INFO_SUCCESS',
  GET_GLOBAL_INFO_FAILURE: 'GET_GLOBAL_INFO_FAILURE',
  
  GET_GEODATA: 'GET_GEODATA',
  GET_GEODATA_REQUEST: 'GET_GEODATA_REQUEST',
  GET_GEODATA_SUCCESS: 'GET_GEODATA_SUCCESS',
  GET_GEODATA_FAILURE: 'GET_GEODATA_FAILURE',

  UPLOAD_ATTACH_FILE: 'UPLOAD_ATTACH_FILE',
  UPLOAD_ATTACH_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_ATTACH_FILE_SUCCESS: 'UPLOAD_ATTACH_FILE_SUCCESS',
  UPLOAD_ATTACH_FILE_FAILURE: 'UPLOAD_ATTACH_FILE_FAILURE',
  
  LOG_OUT: 'LOG_OUT',
};
