export default {
  GET_GLOBAL_INFO: 'GET_GLOBAL_INFO',
  GET_GLOBAL_INFO_REQUEST: 'GET_GLOBAL_INFO_REQUEST',
  GET_GLOBAL_INFO_SUCCESS: 'GET_GLOBAL_INFO_SUCCESS',
  GET_GLOBAL_INFO_FAILURE: 'GET_GLOBAL_INFO_FAILURE',
  
  GET_AVAILABILITIES: 'GET_AVAILABILITIES',
  GET_AVAILABILITIES_REQUEST: 'GET_AVAILABILITIES_REQUEST',
  GET_AVAILABILITIES_SUCCESS: 'GET_AVAILABILITIES_SUCCESS',
  GET_AVAILABILITIES_FAILURE: 'GET_AVAILABILITIES_FAILURE',

  GET_RATES: 'GET_RATES',
  GET_RATES_REQUEST: 'GET_RATES_REQUEST',
  GET_RATES_SUCCESS: 'GET_RATES_SUCCESS',
  GET_RATES_FAILURE: 'GET_RATES_FAILURE',

  GET_SERVICES: 'GET_SERVICES',
  GET_SERVICES_REQUEST: 'GET_SERVICES_REQUEST',
  GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
  GET_SERVICES_FAILURE: 'GET_SERVICES_FAILURE',

  GET_GEODATA: 'GET_GEODATA',
  GET_GEODATA_REQUEST: 'GET_GEODATA_REQUEST',
  GET_GEODATA_SUCCESS: 'GET_GEODATA_SUCCESS',
  GET_GEODATA_FAILURE: 'GET_GEODATA_FAILURE',

  UPLOAD_ATTACH_FILE: 'UPLOAD_ATTACH_FILE',
  UPLOAD_ATTACH_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_ATTACH_FILE_SUCCESS: 'UPLOAD_ATTACH_FILE_SUCCESS',
  UPLOAD_ATTACH_FILE_FAILURE: 'UPLOAD_ATTACH_FILE_FAILURE',
  
  LOG_OUT: 'LOG_OUT',
};
