export default {
  GET_JOB: 'GET_JOB',
  GET_JOB_REQUEST: 'GET_JOB_REQUEST',
  GET_JOB_SUCCESS: 'GET_JOB_SUCCESS',
  GET_JOB_FAILURE: 'GET_JOB_FAILURE',  

  GET_MY_JOBS: 'GET_MY_JOBS',
  GET_MY_JOBS_REQUEST: 'GET_MY_JOBS_REQUEST',
  GET_MY_JOBS_SUCCESS: 'GET_MY_JOBS_SUCCESS',
  GET_MY_JOBS_FAILURE: 'GET_MY_JOBS_FAILURE',  

  GET_JOBS_BY_ZIPCODE: 'GET_JOBS_BY_ZIPCODE',
  GET_JOBS_BY_ZIPCODE_REQUEST: 'GET_JOBS_BY_ZIPCODE_REQUEST',
  GET_JOBS_BY_ZIPCODE_SUCCESS: 'GET_JOBS_BY_ZIPCODE_SUCCESS',
  GET_JOBS_BY_ZIPCODE_FAILURE: 'GET_JOBS_BY_ZIPCODE_FAILURE',

  CREATE_NEW_JOB: 'CREATE_NEW_JOB',
  CREATE_NEW_JOB_REQUEST: 'CREATE_NEW_JOB_REQUEST',
  CREATE_NEW_JOB_SUCCESS: 'CREATE_NEW_JOB_SUCCESS',
  CREATE_NEW_JOB_FAILURE: 'CREATE_NEW_JOB_FAILURE',

  CANCEL_JOB: 'CANCEL_JOB',
  CANCEL_JOB_REQUEST: 'CANCEL_JOB_REQUEST',
  CANCEL_JOB_SUCCESS: 'CANCEL_JOB_SUCCESS',
  CANCEL_JOB_FAILURE: 'CANCEL_JOB_FAILURE',

  GET_PROPOSED_JOBS: 'GET_PROPOSED_JOBS',
  GET_PROPOSED_JOBS_REQUEST: 'GET_PROPOSED_JOBS_REQUEST',
  GET_PROPOSED_JOBS_SUCCESS: 'GET_PROPOSED_JOBS_SUCCESS',
  GET_PROPOSED_JOBS_FAILURE: 'GET_PROPOSED_JOBS_FAILURE',

  APPLY_JOB: 'APPLY_JOB',
  APPLY_JOB_REQUEST: 'APPLY_JOB_REQUEST',
  APPLY_JOB_SUCCESS: 'APPLY_JOB_SUCCESS',
  APPLY_JOB_FAILURE: 'APPLY_JOB_FAILURE',

  WITHDRAW_JOB: 'WITHDRAW_JOB',
  WITHDRAW_JOB_REQUEST: 'WITHDRAW_JOB_REQUEST',
  WITHDRAW_JOB_SUCCESS: 'WITHDRAW_JOB_SUCCESS',
  WITHDRAW_JOB_FAILURE: 'WITHDRAW_JOB_FAILURE',

  HIRE: 'HIRE',
  HIRE_REQUEST: 'HIRE_REQUEST',
  HIRE_SUCCESS: 'HIRE_SUCCESS',
  HIRE_FAILURE: 'HIRE_FAILURE',

  CANCEL_OFFER: 'CANCEL_OFFER',
  CANCEL_OFFER_REQUEST: 'CANCEL_OFFER_REQUEST',
  CANCEL_OFFER_SUCCESS: 'CANCEL_OFFER_SUCCESS',
  CANCEL_OFFER_FAILURE: 'CANCEL_OFFER_FAILURE',

  ACCEPT_OFFER: 'ACCEPT_OFFER',
  ACCEPT_OFFER_REQUEST: 'ACCEPT_OFFER_REQUEST',
  ACCEPT_OFFER_SUCCESS: 'ACCEPT_OFFER_SUCCESS',
  ACCEPT_OFFER_FAILURE: 'ACCEPT_OFFER_FAILURE',

  DECLINE_OFFER: 'DECLINE_OFFER',
  DECLINE_OFFER_REQUEST: 'DECLINE_OFFER_REQUEST',
  DECLINE_OFFER_SUCCESS: 'DECLINE_OFFER_SUCCESS',
  DECLINE_OFFER_FAILURE: 'DECLINE_OFFER_FAILURE',

  UPDATE_JOB: 'UPDATE_JOB',
  UPDATE_JOB_REQUEST: 'UPDATE_JOB_REQUEST',
  UPDATE_JOB_SUCCESS: 'UPDATE_JOB_SUCCESS',
  UPDATE_JOB_FAILURE: 'UPDATE_JOB_FAILURE',

  PAY_JOB: 'PAY_JOB',
  PAY_JOB_REQUEST: 'PAY_JOB_REQUEST',
  PAY_JOB_SUCCESS: 'PAY_JOB_SUCCESS',
  PAY_JOB_FAILURE: 'PAY_JOB_FAILURE',

  WRITE_REVIEW: 'WRITE_REVIEW',
  WRITE_REVIEW_REQUEST: 'WRITE_REVIEW_REQUEST',
  WRITE_REVIEW_SUCCESS: 'WRITE_REVIEW_SUCCESS',
  WRITE_REVIEW_FAILURE: 'WRITE_REVIEW_FAILURE',

  SET_SELECTED_JOB: 'SET_SELECTED_JOB',
  RESET_JOB: 'RESET_JOB',
};
