export default {
  GET_UNREADNUMBER: 'GET_UNREADNUMBER',
  GET_UNREADNUMBER_REQUEST: 'GET_UNREADNUMBER_REQUEST',
  GET_UNREADNUMBER_SUCCESS: 'GET_UNREADNUMBER_SUCCESS',
  GET_UNREADNUMBER_FAILURE: 'GET_UNREADNUMBER_FAILURE',

  CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
  CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST',
  CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
  CREATE_NOTIFICATION_FAILURE: 'CREATE_NOTIFICATION_FAILURE',

  GET_MY_NOTIFICATIONS: 'GET_MY_NOTIFICATIONS',
  GET_MY_NOTIFICATIONS_REQUEST: 'GET_MY_NOTIFICATIONS_REQUEST',
  GET_MY_NOTIFICATIONS_SUCCESS: 'GET_MY_NOTIFICATIONS_SUCCESS',
  GET_MY_NOTIFICATIONS_FAILURE: 'GET_MY_NOTIFICATIONS_FAILURE',

  MARK_READ_NOTIFICATION: 'MARK_READ_NOTIFICATION',
  MARK_READ_NOTIFICATION_REQUEST: 'MARK_READ_NOTIFICATION_REQUEST',
  MARK_READ_NOTIFICATION_SUCCESS: 'MARK_READ_NOTIFICATION_SUCCESS',
  MARK_READ_NOTIFICATION_FAILURE: 'MARK_READ_NOTIFICATION_FAILURE',

  RESET_NOTIFICATION: 'RESET_NOTIFICATION',
};
