export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  RESTORE_USER: 'RESTORE_USER',
  RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
  RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
  RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VERIFY_CODE_PASSWORD: 'VERIFY_CODE_PASSWORD',
  VERIFY_CODE_PASSWORD_REQUEST: 'VERIFY_CODE_PASSWORD_REQUEST',
  VERIFY_CODE_PASSWORD_SUCCESS: 'VERIFY_CODE_PASSWORD_SUCCESS',
  VERIFY_CODE_PASSWORD_FAILURE: 'VERIFY_CODE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_REQUEST: 'CHECK_EMAIL_REQUEST',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_PLAYER_ID: 'SET_PLAYER_ID',
  SET_ZIPCODE: 'SET_ZIPCODE',
  SET_UNREAD_MESSAGE: 'SET_UNREAD_MESSAGE',
  
  RESET_USER: 'RESET_USER',
};
