export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  RESTORE_USER: 'RESTORE_USER',
  RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
  RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
  RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',

  REGISTER_CUSTOMER: 'REGISTER_CUSTOMER',
  REGISTER_CUSTOMER_REQUEST: 'REGISTER_CUSTOMER_REQUEST',
  REGISTER_CUSTOMER_SUCCESS: 'REGISTER_CUSTOMER_SUCCESS',
  REGISTER_CUSTOMER_FAILURE: 'REGISTER_CUSTOMER_FAILURE',

  REGISTER_PROVIDER: 'REGISTER_PROVIDER',
  REGISTER_PROVIDER_REQUEST: 'REGISTER_PROVIDER_REQUEST',
  REGISTER_PROVIDER_SUCCESS: 'REGISTER_PROVIDER_SUCCESS',
  REGISTER_PROVIDER_FAILURE: 'REGISTER_PROVIDER_FAILURE',

  CREATE_USER: 'CREATE_USER',
  CREATE_USER_REQUEST: 'CREATE_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_FAILURE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VERIFY_CODE_PASSWORD: 'VERIFY_CODE_PASSWORD',
  VERIFY_CODE_PASSWORD_REQUEST: 'VERIFY_CODE_PASSWORD_REQUEST',
  VERIFY_CODE_PASSWORD_SUCCESS: 'VERIFY_CODE_PASSWORD_SUCCESS',
  VERIFY_CODE_PASSWORD_FAILURE: 'VERIFY_CODE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILURE: 'UPDATE_CUSTOMER_FAILURE',

  UPDATE_PROVIDER: 'UPDATE_PROVIDER',
  UPDATE_PROVIDER_REQUEST: 'UPDATE_PROVIDER_REQUEST',
  UPDATE_PROVIDER_SUCCESS: 'UPDATE_PROVIDER_SUCCESS',
  UPDATE_PROVIDER_FAILURE: 'UPDATE_PROVIDER_FAILURE',

  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  GET_TRANSACTIONS_REQUEST: 'GET_TRANSACTIONS_REQUEST',
  GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
  GET_TRANSACTIONS_FAILURE: 'GET_TRANSACTIONS_FAILURE',

  WITHDRAW_WITH_PAYPAL: 'WITHDRAW_WITH_PAYPAL',
  WITHDRAW_WITH_PAYPAL_REQUEST: 'WITHDRAW_WITH_PAYPAL_REQUEST',
  WITHDRAW_WITH_PAYPAL_SUCCESS: 'WITHDRAW_WITH_PAYPAL_SUCCESS',
  WITHDRAW_WITH_PAYPAL_FAILURE: 'WITHDRAW_WITH_PAYPAL_FAILURE',

  WITHDRAW_WITH_BANK: 'WITHDRAW_WITH_BANK',
  WITHDRAW_WITH_BANK_REQUEST: 'WITHDRAW_WITH_BANK_REQUEST',
  WITHDRAW_WITH_BANK_SUCCESS: 'WITHDRAW_WITH_BANK_SUCCESS',
  WITHDRAW_WITH_BANK_FAILURE: 'WITHDRAW_WITH_BANK_FAILURE',

  DEPOSIT: 'DEPOSIT',
  DEPOSIT_REQUEST: 'DEPOSIT_REQUEST',
  DEPOSIT_SUCCESS: 'DEPOSIT_SUCCESS',
  DEPOSIT_FAILURE: 'DEPOSIT_FAILURE',

  GET_PAYPAL_CLIENT_TOKEN: 'GET_PAYPAL_CLIENT_TOKEN',
  GET_PAYPAL_CLIENT_TOKEN_REQUEST: 'GET_PAYPAL_CLIENT_TOKEN_REQUEST',
  GET_PAYPAL_CLIENT_TOKEN_SUCCESS: 'GET_PAYPAL_CLIENT_TOKEN_SUCCESS',
  GET_PAYPAL_CLIENT_TOKEN_FAILURE: 'GET_PAYPAL_CLIENT_TOKEN_FAILURE',

  PROCESS_PAYPAL_DEPOSIT: 'PROCESS_PAYPAL_DEPOSIT',
  PROCESS_PAYPAL_DEPOSIT_REQUEST: 'PROCESS_PAYPAL_DEPOSIT_REQUEST',
  PROCESS_PAYPAL_DEPOSIT_SUCCESS: 'PROCESS_PAYPAL_DEPOSIT_SUCCESS',
  PROCESS_PAYPAL_DEPOSIT_FAILURE: 'PROCESS_PAYPAL_DEPOSIT_FAILURE',

  GET_NEARBY_PROVIDERS: 'GET_NEARBY_PROVIDERS',
  GET_NEARBY_PROVIDERS_REQUEST: 'GET_NEARBY_PROVIDERS_REQUEST',
  GET_NEARBY_PROVIDERS_SUCCESS: 'GET_NEARBY_PROVIDERS_SUCCESS',
  GET_NEARBY_PROVIDERS_FAILURE: 'GET_NEARBY_PROVIDERS_FAILURE',

  GET_CURRENT_USER: 'GET_CURRENT_USER',
  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_REQUEST: 'CHECK_EMAIL_REQUEST',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_PLAYER_ID: 'SET_PLAYER_ID',
  SET_GEO_LOCATION: 'SET_GEO_LOCATION',
  SET_ZIPCODE: 'SET_ZIPCODE',
  SET_UNREAD_MESSAGE: 'SET_UNREAD_MESSAGE',
  
  RESET_USER: 'RESET_USER',
};
