export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGIN_WITH_SOCIAL: 'LOGIN_WITH_SOCIAL',
  LOGIN_WITH_SOCIAL_REQUEST: 'LOGIN_WITH_SOCIAL_REQUEST',
  LOGIN_WITH_SOCIAL_SUCCESS: 'LOGIN_WITH_SOCIAL_SUCCESS',
  LOGIN_WITH_SOCIAL_FAILURE: 'LOGIN_WITH_SOCIAL_FAILURE',

  RESTORE_USER: 'RESTORE_USER',
  RESTORE_USER_REQUEST: 'RESTORE_USER_REQUEST',
  RESTORE_USER_SUCCESS: 'RESTORE_USER_SUCCESS',
  RESTORE_USER_FAILURE: 'RESTORE_USER_FAILURE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  VERIFY_CODE_PASSWORD: 'VERIFY_CODE_PASSWORD',
  VERIFY_CODE_PASSWORD_REQUEST: 'VERIFY_CODE_PASSWORD_REQUEST',
  VERIFY_CODE_PASSWORD_SUCCESS: 'VERIFY_CODE_PASSWORD_SUCCESS',
  VERIFY_CODE_PASSWORD_FAILURE: 'VERIFY_CODE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  GET_USER: 'GET_USER',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  GET_USER_BY_EMAIL_REQUEST: 'GET_USER_BY_EMAIL_REQUEST',
  GET_USER_BY_EMAIL_SUCCESS: 'GET_USER_BY_EMAIL_SUCCESS',
  GET_USER_BY_EMAIL_FAILURE: 'GET_USER_BY_EMAIL_FAILURE',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  CHECK_EMAIL: 'CHECK_EMAIL',
  CHECK_EMAIL_REQUEST: 'CHECK_EMAIL_REQUEST',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE: 'CHECK_EMAIL_FAILURE',

  IMPORT_CONTACTS: 'IMPORT_CONTACTS',
  IMPORT_CONTACTS_REQUEST: 'IMPORT_CONTACTS_REQUEST',
  IMPORT_CONTACTS_SUCCESS: 'IMPORT_CONTACTS_SUCCESS',
  IMPORT_CONTACTS_FAILURE: 'IMPORT_CONTACTS_FAILURE',

  ADD_CONTACT: 'ADD_CONTACT',
  ADD_CONTACT_REQUEST: 'ADD_CONTACT_REQUEST',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',

  EDIT_CONTACT: 'EDIT_CONTACT',
  EDIT_CONTACT_REQUEST: 'EDIT_CONTACT_REQUEST',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  EDIT_CONTACT_FAILURE: 'EDIT_CONTACT_FAILURE',

  REMOVE_CONTACT: 'REMOVE_CONTACT',
  REMOVE_CONTACT_REQUEST: 'REMOVE_CONTACT_REQUEST',
  REMOVE_CONTACT_SUCCESS: 'REMOVE_CONTACT_SUCCESS',
  REMOVE_CONTACT_FAILURE: 'REMOVE_CONTACT_FAILURE',

  SEND_INVITE: 'SEND_INVITE',
  SEND_INVITE_REQUEST: 'SEND_INVITE_REQUEST',
  SEND_INVITE_SUCCESS: 'SEND_INVITE_SUCCESS',
  SEND_INVITE_FAILURE: 'SEND_INVITE_FAILURE',

  GET_CONTACT_STATUS: 'GET_CONTACT_STATUS',
  GET_CONTACT_STATUS_REQUEST: 'GET_CONTACT_STATUS_REQUEST',
  GET_CONTACT_STATUS_SUCCESS: 'GET_CONTACT_STATUS_SUCCESS',
  GET_CONTACT_STATUS_FAILURE: 'GET_CONTACT_STATUS_FAILURE',

  GET_MY_FRIENDS: 'GET_MY_FRIENDS',
  GET_MY_FRIENDS_REQUEST: 'GET_MY_FRIENDS_REQUEST',
  GET_MY_FRIENDS_SUCCESS: 'GET_MY_FRIENDS_SUCCESS',
  GET_MY_FRIENDS_FAILURE: 'GET_MY_FRIENDS_FAILURE',

  GET_FRIEND_COUNT: 'GET_FRIEND_COUNT',
  GET_FRIEND_COUNT_REQUEST: 'GET_FRIEND_COUNT_REQUEST',
  GET_FRIEND_COUNT_SUCCESS: 'GET_FRIEND_COUNT_SUCCESS',
  GET_FRIEND_COUNT_FAILURE: 'GET_FRIEND_COUNT_FAILURE',

  SEND_FRIEND_REQUEST: 'SEND_FRIEND_REQUEST',
  SEND_FRIEND_REQUEST_REQUEST: 'SEND_FRIEND_REQUEST_REQUEST',
  SEND_FRIEND_REQUEST_SUCCESS: 'SEND_FRIEND_REQUEST_SUCCESS',
  SEND_FRIEND_REQUEST_FAILURE: 'SEND_FRIEND_REQUEST_FAILURE',

  ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
  ACCEPT_FRIEND_REQUEST_REQUEST: 'ACCEPT_FRIEND_REQUEST_REQUEST',
  ACCEPT_FRIEND_REQUEST_SUCCESS: 'ACCEPT_FRIEND_REQUEST_SUCCESS',
  ACCEPT_FRIEND_REQUEST_FAILURE: 'ACCEPT_FRIEND_REQUEST_FAILURE',

  DECLINE_FRIEND_REQUEST: 'DECLINE_FRIEND_REQUEST',
  DECLINE_FRIEND_REQUEST_REQUEST: 'DECLINE_FRIEND_REQUEST_REQUEST',
  DECLINE_FRIEND_REQUEST_SUCCESS: 'DECLINE_FRIEND_REQUEST_SUCCESS',
  DECLINE_FRIEND_REQUEST_FAILURE: 'DECLINE_FRIEND_REQUEST_FAILURE',

  REMOVE_FRIEND: 'REMOVE_FRIEND',
  REMOVE_FRIEND_REQUEST: 'REMOVE_FRIEND_REQUEST',
  REMOVE_FRIEND_SUCCESS: 'REMOVE_FRIEND_SUCCESS',
  REMOVE_FRIEND_FAILURE: 'REMOVE_FRIEND_FAILURE',

  CHANGE_SUBSCRIPTION: 'CHANGE_SUBSCRIPTION',
  CHANGE_SUBSCRIPTION_REQUEST: 'CHANGE_SUBSCRIPTION_REQUEST',
  CHANGE_SUBSCRIPTION_SUCCESS: 'CHANGE_SUBSCRIPTION_SUCCESS',
  CHANGE_SUBSCRIPTION_FAILURE: 'CHANGE_SUBSCRIPTION_FAILURE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_PLAYER_ID: 'SET_PLAYER_ID',
  SET_ZIPCODE: 'SET_ZIPCODE',
  SET_UNREAD_MESSAGE: 'SET_UNREAD_MESSAGE',
  CHANGE_FRIEND_ACTIVE_PAGE: 'CHANGE_FRIEND_ACTIVE_PAGE',
  RESET_FRIEND_PAGE: 'RESET_FRIEND_PAGE',

  RESET_USER: 'RESET_USER',
};
