const Images = {
    logo01: require('../../assets/images/logo01.png'),
    btn_google_plus: require('../../assets/images/btn_google_plus.png'),
    btn_facebook: require('../../assets/images/btn_facebook.png'),
    email_icon: require('../../assets/images/email_icon.png'),
    password_icon: require('../../assets/images/password_icon.png'),
    checkbox_selected: require('../../assets/images/checkbox_selected.png'),
    checkbox_normal: require('../../assets/images/checkbox_normal.png'),
    eye_icon: require('../../assets/images/eye_icon.png'),
    eye_hide_icon: require('../../assets/images/eye_hide_icon.png'),
    back_arrow: require('../../assets/images/back_arrow.png'),
    dropdown_icon: require('../../assets/images/dropdown_icon.png'),
    account_icon: require('../../assets/images/account_icon.png'),

    // photo_icon: require('../../assets/images/photo_icon.png'),
    // bank_icon: require('../../assets/images/bank_icon.png'),
    // red_close_button: require('../../assets/images/red_close_button.png'),
    // tick: require('../../assets/images/tick.png'),    
    // tick_white: require('../../assets/images/tick_white.png'),    
    // close_icon: require('../../assets/images/close_icon.png'),        
    // sad: require('../../assets/images/sad.png'),        
    // notification_icon: require('../../assets/images/notification_icon.png'),        
    // search_icon: require('../../assets/images/search_icon.png'),  
    // paypal: require('../../assets/images/paypal.png'),
    // small_bank_icon: require('../../assets/images/small_bank_icon.png'),          
    // credit_card: require('../../assets/images/credit-card.png'),    
    // arrow_right: require('../../assets/images/arrow_right.png'),    
    // star_selected: require('../../assets/images/star_selected.png'),    
    // star_icon: require('../../assets/images/star_icon.png'),    
    // white_photo_icon: require('../../assets/images/white_photo_icon.png'),    
    // dollar_icon: require('../../assets/images/dollar_icon.png'),    
    // timer_icon: require('../../assets/images/timer_icon.png'),    
    // tab_home: require('../../assets/images/tab_home.png'),    
    // tab_home_selected: require('../../assets/images/tab_home_selected.png'),    
    // tab_history: require('../../assets/images/tab_history.png'),    
    // tab_history_selected: require('../../assets/images/tab_history_selected.png'),   
    // tab_settings: require('../../assets/images/tab_settings.png'),    
    // tab_settings_selected: require('../../assets/images/tab_settings_selected.png'),    
    // placeholder_image: require('../../assets/images/placeholder_image.png'),
    // type_customer_selected: require('../../assets/images/type_customer_selected.png'),
    // type_customer: require('../../assets/images/type_customer.png'),    
    // type_provider_selected: require('../../assets/images/type_provider_selected.png'),
    // type_provider: require('../../assets/images/type_provider.png'),
    // map_pin: require('../../assets/images/map_pin.png'),
    // pin_icon: require('../../assets/images/pin_icon.png'),
    // chat_icon: require('../../assets/images/chat_icon.png'),
    // image_record_icon: require('../../assets/images/image_record_icon.png'),
    // audio_record_icon: require('../../assets/images/audio_record_icon.png'),
    // record_board: require('../../assets/images/record_board.png'),
    // send_icon: require('../../assets/images/send_icon.png'),
    // walkie_talkie_icon: require('../../assets/images/walkie_talkie_icon.png'),
    // play_black: require('../../assets/images/play_black.png'),
    // play_white: require('../../assets/images/play_white.png'),
    // stop_black: require('../../assets/images/stop_black.png'),
    // stop_white: require('../../assets/images/stop_white.png'),
    // ico_address: require('../../assets/images/ico_address.png'),
    // ico_mail: require('../../assets/images/ico_mail.png'),
    // ico_phone: require('../../assets/images/ico_phone.png'),
};

export default Images;
