const Images = {
    logo01: require('../../assets/images/logo01.png'),
    btn_google_plus: require('../../assets/images/btn_google_plus.png'),
    btn_facebook: require('../../assets/images/btn_facebook.png'),
    email_icon: require('../../assets/images/email_icon.png'),
    password_icon: require('../../assets/images/password_icon.png'),
    checkbox_selected: require('../../assets/images/checkbox_selected.png'),
    checkbox_normal: require('../../assets/images/checkbox_normal.png'),
    eye_icon: require('../../assets/images/eye_icon.png'),
    eye_hide_icon: require('../../assets/images/eye_hide_icon.png'),
    back_arrow: require('../../assets/images/back_arrow.png'),
    back_arrow_white: require('../../assets/images/back_arrow_white.png'),
    dropdown_icon: require('../../assets/images/dropdown_icon.png'),
    account_icon: require('../../assets/images/account_icon.png'),
    tab_friend: require('../../assets/images/tab_friend.png'),    
    tab_friend_selected: require('../../assets/images/tab_friend_selected.png'),    
    tab_contact: require('../../assets/images/tab_contact.png'),    
    tab_contact_selected: require('../../assets/images/tab_contact_selected.png'),    
    tab_message: require('../../assets/images/tab_message.png'),    
    tab_message_selected: require('../../assets/images/tab_message_selected.png'),   
    tab_profile: require('../../assets/images/tab_profile.png'),    
    tab_profile_selected: require('../../assets/images/tab_profile_selected.png'),    
    tab_settings: require('../../assets/images/tab_settings.png'),    
    tab_settings_selected: require('../../assets/images/tab_settings_selected.png'),    
    tab_notification: require('../../assets/images/tab_notification.png'),    
    tab_notification_selected: require('../../assets/images/tab_notification_selected.png'),    
    search_icon: require('../../assets/images/search_icon.png'),  
    arrow_right: require('../../assets/images/arrow_right.png'),    
    icon_notification: require('../../assets/images/icon_notification.png'),
    icon_password: require('../../assets/images/icon_password.png'),
    icon_profile: require('../../assets/images/icon_profile.png'),
    icon_subscription: require('../../assets/images/icon_subscription.png'),
    icon_plus: require('../../assets/images/icon_plus.png'),
    close_icon: require('../../assets/images/close_icon.png'),        
    sad: require('../../assets/images/sad.png'),        
    chat_icon: require('../../assets/images/chat_icon.png'),
    image_record_icon: require('../../assets/images/image_record_icon.png'),
    send_icon: require('../../assets/images/send_icon.png'),
    icon_clock: require('../../assets/images/icon_clock.png'),
    icon_calendar: require('../../assets/images/icon_calendar.png'),
    icon_privacy: require('../../assets/images/icon_privacy.png'),
    icon_terms: require('../../assets/images/icon_terms.png'),
    icon_search: require('../../assets/images/icon_search.png'),
    circle_close: require('../../assets/images/circle_close.png'),
    icon_red_trash: require('../../assets/images/icon_red_trash.png'),
    icon_white_back: require('../../assets/images/icon_white_back.png'),
    
};

export default Images;
